### ISSUE TITLE
RuntimeError: The size of tensor a (50) must match the size of tensor b (25) at non-singleton dimension 0

### ISSUE THREAD

**Issue by KevinWang676** [thuhcsi/NeuCoSVC#10]
Hi, when I ran the inference code `python infer.py --src_wav_path me.wav --ref_wav_path music.mp3 --out_path output.wav`, I got the error `RuntimeError: The size of tensor a (50) must match the size of tensor b (25) at non-singleton dimension 0`.

Do you know how I can solve this issue? Thank you!

```
Traceback (most recent call last):
  File "/content/NeuCoSVC/infer.py", line 153, in <module>
    VoiceConverter(test_utt=args.src_wav_path, ref_utt=args.ref_wav_path, out_path=args.out_path,
  File "/content/NeuCoSVC/infer.py", line 44, in VoiceConverter
    query_feats = wavlm_encoder.get_features(test_utt, weights=applied_weights)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/NeuCoSVC/modules/wavlm_encoder.py", line 97, in get_features
    features = (features*weights[:, None] ).sum(dim=0) # (1, seq_len, dim)
RuntimeError: The size of tensor a (50) must match the size of tensor b (25) at non-singleton dimension 0

```

**Comment by KevinWang676** [comment]
Hi, @lixucuhk and @jerry1331 Can you take some time look into this issue? Thanks!

**Comment by jerry1331** [comment]
It seems that you have passed in an incorrect `features`, its shape should be [25, T, 1024], where 25 is the number of layers of the wavlm encoder. Have you made any modifications to the modules/wavlm_encoder.py file? Please provide me with the modified content so that I can better assist you.

**Comment by NZqian** [comment]
I ran into the same problem and fond the reason is that I was inputting mono channel audio XD

**Comment by KevinWang676** [comment]
@jerry1331 @NZqian Thanks for your replies. I found that I got the error because my input audio is multi-channel. And your program only works for mono-channel input audio. Maybe you need to specify it in the README. Thanks for your help!

**Comment by jerry1331** [comment]
I have updated the README to add the mono audio requirement. Thanks for your suggestion!

**Comment by KevinWang676** [comment]
@jerry1331 Thank you! I wonder if we can have a further discussion on NeuCoSVC like the architecture and potential applications. I have made a [video](https://bilibili.com/video/BV1h5411q79Y) to introduce NeuCoSVC to my audience before and I am very interested in it up to now. My WeChat is Kevin985676. Please feel free to contact me.

**Comment by lixucuhk** [comment]
> @jerry1331 Thank you! I wonder if we can have a further discussion on NeuCoSVC like the architecture and potential applications. I have made a [video](https://bilibili.com/video/BV1h5411q79Y) to introduce NeuCoSVC to my audience before and I am very interested in it up to now. My WeChat is Kevin985676. Please feel free to contact me.

Thank you for your enthusiasm! Absolutely, we are keen to delve into the potential applications and amplify the impact of our project. Your support is greatly appreciated!
