### ISSUE TITLE
No such file or directory: ''

### ISSUE THREAD

**Issue by KevinWang676** [thuhcsi/NeuCoSVC#2]
Hi, when I ran the code `python infer.py --src_wav_path "audio1.wav" --ref_wav_path "audio2.wav" --out_path "output.wav"`, the following error occurred. Could you help me resolve this issue? Thanks!

![image](https://github.com/thuhcsi/NeuCoSVC/assets/126712357/d321d8d2-1b90-4a8d-a9f2-9c11634000b5)

**Comment by jerry1331** [comment]
Changing the output address to "./out_path" can solve your problem. In addition, I have fixed the bug in a new commit. There is no problem in using "out_path" directly after pull. Thank you for supporting our project.

**Comment by jerry1331** [comment]
Changing the output address to "./output.wav" can solve your problem. In addition, I have fixed the bug in a new commit. There is no problem in using "output.wav" directly after pull. Thank you for supporting our project.

**Comment by jerry1331** [comment]
Changing the out_path to "./output.wav" can solve your problem. In addition, I have fixed the bug in a new commit. There is no problem in using "output.wav" directly after pull. Thank you for supporting our project.

**Comment by KevinWang676** [comment]
Thank you! In addition, I wonder how to directly use the `reaper` file instead of running the following code every time. Can I just download the folder that contains `reaper` and specify its path in [utils/pitch_ld_extraction.py](https://github.com/thuhcsi/NeuCoSVC/blob/master/utils/pitch_ld_extraction.py)? I tried to do so, but failed.

```
git clone https://github.com/google/REAPER.git
cd REAPER
mkdir build   # In the REAPER top-level directory
cd build
cmake ..
make
```

**Comment by jerry1331** [comment]
> Thank you! In addition, I wonder how to directly use the `reaper` file instead of running the following code every time. Can I just download the folder that contains `reaper` and specify its path in [utils/pitch_ld_extraction.py](https://github.com/thuhcsi/NeuCoSVC/blob/master/utils/pitch_ld_extraction.py)? I tried to do so, but failed.
> 
> ```
> git clone https://github.com/google/REAPER.git
> cd REAPER
> mkdir build   # In the REAPER top-level directory
> cd build
> cmake ..
> make
> ```

You only need to execute the above code to compile once, and then copy the path of the `reaper` to the [utils/pitch_ld_extraction.py](https://github.com/thuhcsi/NeuCoSVC/blob/master/utils/pitch_ld_extraction.py)' file. 
Please verify if your reaper path is correct or provide us with more error information for further assistance.

**Comment by KevinWang676** [comment]
Hi @jerry1331, I ran the above code and got the `reaper` file [here](https://huggingface.co/spaces/kevinwang676/NeuCoSVC-Colab/tree/main/reaper-tmp/REAPER/build). I specified the path [here](https://huggingface.co/spaces/kevinwang676/NeuCoSVC-Colab/blob/main/utils/pitch_ld_extraction.py#L60).

However, I could not do the voice conversion step. You may try the demo I made via this [link](https://huggingface.co/spaces/kevinwang676/NeuCoSVC-Colab). Thanks!

![image](https://github.com/thuhcsi/NeuCoSVC/assets/126712357/5c6670c7-66ce-48b4-ab7c-2df5a16c8498)

**Comment by lixucuhk** [comment]
Hi Kevin, could you please provide the whole inference command? Let me check the problem.
