### ISSUE TITLE
The quality of svc

### ISSUE THREAD

**Issue by Alidaling** [thuhcsi/NeuCoSVC#4]
Thank you very much for sharing your work, it looks very informative and helpful. However, when I tested the model you provided, it seems like the audio quality is not as good as the demo effect you provided. Did I do something wrong? Looking forward to your reply.
model：
![image](https://github.com/thuhcsi/NeuCoSVC/assets/131933121/9e30e6a1-d1b3-43eb-9e42-ef1430187ccd)
infer：
python infer.py --src_wav_path  source.wav  --ref_wav_path target.wav --out_path out-path/svc.wav
The source.wav and target.wav are come from your demo web

**Comment by lixucuhk** [comment]
Hi Alidaling, thank you for your interest and question!
I'm curious about the source/target audio you utilized for inference. Did they originate from intra-language, cross-language, or cross-domain scenarios? Please be aware that the reference audio in intra-/cross-language scenarios is approximately 10 minutes long, while the one in the cross-domain scenario is about 30 seconds long, as mentioned in Section 4 of our paper. In the demo web, we've only included a single segment of the target person's audio to demonstrate their voice characteristics. 
For a quick testing and performance comparison, please feel free to use the source/target audio mentioned in the duration study section. Apologies for any confusion caused!

**Comment by Ryu1845** [comment]
Do you know how much GPU memory is required to load the 10 minutes of audio? (I could only load ~90s on my 8GB GPU, but I might have done something wrong)

**Comment by lixucuhk** [comment]
Hi, thank you for your question!
My recommendation would be to initially divide the audio into smaller segments. Following this, extract the WavLM features from each segment and store them as a reference matching pool for the inference stage. This approach should be compatible with any GPU capacity.

**Comment by Alidaling** [comment]
> Section 4
Thank you very much for your reply!The source/target audio I'm using is from the intra-language. May I ask why you used 10-minute-long audio? Would the effect be better this way? Doesn't the paper suggest that the optimal effect is achieved with 60-second audio, and that the effect diminishes beyond 60 seconds?Looking forward to your reply.
![image](https://github.com/thuhcsi/NeuCoSVC/assets/131933121/3304acbd-9748-422a-862a-7a61a681942d)

**Comment by lixucuhk** [comment]
> > Section 4
> > Thank you very much for your reply!The source/target audio I'm using is from the intra-language. May I ask why you used 10-minute-long audio? Would the effect be better this way? Doesn't the paper suggest that the optimal effect is achieved with 60-second audio, and that the effect diminishes beyond 60 seconds?Looking forward to your reply.
> > ![image](https://private-user-images.githubusercontent.com/131933121/294437188-3304acbd-9748-422a-862a-7a61a681942d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjY4NTIsIm5iZiI6MTcwNDUyNjU1MiwicGF0aCI6Ii8xMzE5MzMxMjEvMjk0NDM3MTg4LTMzMDRhY2JkLTk3NDgtNDIyYS04NjJhLTdhNjFhNjgxOTQyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQwNzM1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjk1ZDM3NmRjOGJhMzQ4OTQ2ZjhiODAyYjM3OGM0ZjU4ODg2N2JhZDIxN2VjOTExNDBkZTdiMDFiZDU5YmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kq7TBrMrpeXDn6XXhKdO5czx3BXx2iDXF7B3gQbClV0)

Good question! In the intra-language evaluation, we simply utilized the full data from each singer to compile the reference audios, which total approximately ten minutes in length. It's important to note that the intra-language, cross-language, and cross-domain evaluations do not focus on the impact of the reference audio length. However, the duration study section does. The test audios in the duration study also originate from the OpenSinger dataset, please have a try. Thank you!

**Comment by lixucuhk** [comment]
Close this issue now, please feel free to reopen it if you have further questions.
