### ISSUE TITLE
About wavlm features

### ISSUE THREAD

**Issue by Kanraaaaa** [thuhcsi/NeuCoSVC#6]
Hi, thanks a lot for sharing your work. But I have met a problem about extracting wavlm feature.
I tried to extract query_feats, matching_set, but features of the last 2 layers (23, 24) are always NaN. My code is as follows:
```
test_utt = 'pretrained/M4_遇见.wav'
ref_utt = 'pretrained/M26.wav'

wavlm_encoder = WavLMEncoder(ckpt_path='pretrained/WavLM-Large.pt', device=device)

query_feats = wavlm_encoder.get_features(test_utt, weights=applied_weights)
matching_set = wavlm_encoder.get_features(ref_utt, weights=applied_weights)
synth_set = wavlm_encoder.get_features(ref_utt, output_layer=SPEAKER_INFORMATION_LAYER)
```

test_utt and ref_utt are downloaded from demo page. 
Have you ever met this problem?

**Comment by jerry1331** [comment]
Hello, I tried extracting the WavLM features directly from the two audio samples on the demo page and did not encounter any NaN values. I suggest checking if there is any issue with the WavLM-Large checkpoint. You can obtain it directly from this link: [WavLM-Large.pt](https://valle.blob.core.windows.net/share/wavlm/WavLM-Large.pt?sv=2020-08-04&st=2023-03-01T07%3A51%3A05Z&se=2033-03-02T07%3A51%3A00Z&sr=c&sp=rl&sig=QJXmSJG9DbMKf48UDIU1MfzIro8HQOf3sqlNXiflY1I%3D).

**Comment by lixucuhk** [comment]
Close this issue now, please feel free to reopen it if you have further questions.
